### ISSUE TITLE
how to install 

### ISSUE THREAD

**Issue by gearcapitan** [KyxRecon/r00tw0rm_react0r_v1.0#1]
![kali linux-2017-04-26-09-40-21](https://cloud.githubusercontent.com/assets/13740942/25440225/63fbb9b0-2a64-11e7-822b-2350c240f6a9.png)

**Comment by KyxRecon** [comment]
Thanks for the report ! 
1- change name script to script.sh
2 . set this command in the same folder ! 
sed -i -e 's/\r$//' script.sh

3 - Enjoy ;) :100:

**Comment by gearcapitan** [comment]
work's, thanks!

**Comment by KyxRecon** [comment]
Thanks for the report :+1:
